# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 강수민
title: Student preparing to become a Junior Backend Developer
email: ramiregi@pusan.ac.kr
website: https://wvssm.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  wvssm
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 백엔드 개발자를 준비하고 있는 강수민입니다. 새로운 기술을 배우는 것을 좋아하며 효율적인 코드를 작성하는 것에 관심이 맞습니다.
  <br>주로 사용하는 언어는 <mark>Java8/11</mark>입니다.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Welcome Page <br>토이프로젝트
        link: https://wvssm.github.io/2-1-Web-Project/
        # link_text: boringcompany.com
        # sub_title: Junior Backend Developer
        caption: 2021.07 ~ 2021.08
        # link_text: Project Website
        additional_links:
          - title:  wvssm/2-1-Web-Project
            icon: fab fa-github
            url: github.com/wvssm/2-1-Web-Project
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          사용자에게 유용한 기능을 추가한 Welcome Page를 구현
          - 시계
          - To do list
          - 날씨, 온도
          - 명언

          <br>기술 스택
          - <mark>HTML</mark>, <mark>CSS</mark>, <mark>Java Script</mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 2023 대구모형<br>전기자율주행자동차<br>경진대회
        sub_title: 차량 제어
        caption: 2023.07~2023.10
        additional_links:
          - title:  wvssm/2023_Self_Driving 
            icon: fab fa-github
            url: github.com/wvssm/2023_Self_Driving 
        description: | 
          자율주행 모형차가 직선 주행, 곡선 주행, 장애물 회피, 신호등 인식을 하도록 제어
          30팀 중 7위
          - 
          - Lidar 제어 장애물 회피 최적화
          - Open CV 신호등 인식 구현
          - PD 제어의 적

          <br>기술 스택
          - <mark>Python</mark>, <mark>Open CV</mark>

      - title: 2022 대구모형<br>전기자율주행자동차<br>경진대회
        sub_title: 차량 제어
        caption: 2022.05~2023.10
        additional_links:
          - title:  wvssm/Daegu-Model-Self-driving
            icon: fab fa-github
            url: github.com/wvssm/Daegu-Model-Self-driving
        description: | 
          자율주행 모형차가 직선 주행, 곡선 주행, 장애물 회피, 신호등 인식을 하도록 제어
          30팀 중 4위

          <br>기술 스택
          - <mark>Python</mark>, <mark>Open CV</mark>

      - title: 2021 UNTACT ARTECH
        sub_title: 시스템 제어
        caption: 2020.12~2021.1
        description: | 
          전신주에 가로등과 태양광 발전을 더한 시제품 제작 참여
          우수상 수상
          - Arduino를 이용하여 조도에 따라 태양광 패널의 개폐와 가로등 점등 제어
          <br>기술 스택
          - <mark>C</mark>
 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 부산대학교
        caption: 2020 - now
        sub_title: 정보컴퓨터공학부
        #quote: >
          #Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - 자료구조, 알고리즘, 운영체제, 컴퓨터구조, 네트워크 등 기본적인 CS 과목 수강
          - 임베디드시스템, 인공지능, 데이터과학 등 다양한 CS 분야의 과목 수강

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
